theme: jekyll-theme-cayman
title: MIKK panel genome analyses
description: Repository containing the code and final results for the MIKK panel genome analyses

plugins:
  - jekyll-readme-index

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
