# Project information
site_name: 'MIKK Panel Genome analyses'
site_description: 'Repository containing the code and the final results for the MIKK panel genome analyses'
site_author: 'Birney Lab'
site_url: 'https://birneylab.github.io/MIKK_genome_paper_analysis/'

# Repository
repo_name: ' birneylab/MIKK_genome_paper_analysis '
repo_url: 'https://github.com/birneylab/MIKK_genome_paper_analysis'

# Navigation menu
nav:
    - Home: index.md
    - Nanopore basecalling: Nanopore_basecalling/index.md
    - Nanopore data processing: Nanopore_processing/index.md
    - Structural variations Nanopore: Nanopore_SV_analysis/index.md
    - DNA methylation analysis: DNA_methylation/index.md
    - Individual MIKK lines hybrid assemblies: Individual_assemblies/index.md
    - Pangenome graph assembly: Graph_assembly/index.md
    - Pangenome graph usage: Graph_usage/index.md
    - Pangenome graph SV analysis: Graph_SV/index.md
    - Licence: licence.md
    - Citation: citation.md

# Theme customization
theme:
    name: 'material'
